# Generated by Django 6.1.1 on 2026-09-26 11:24

import uuid

import django.db.models.deletion
from django.db import migrations, models

import oss_clarity.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                ("domain", models.CharField(max_length=255)),
                ("allowed_hosts", models.JSONField(blank=True, default=list)),
                (
                    "public_key",
                    models.CharField(
                        default=oss_clarity.models.generate_public_key,
                        editable=False,
                        max_length=22,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rejected_hits", models.BigIntegerField(default=0)),
                ("last_rejected_host", models.CharField(blank=True, default="", max_length=255)),
                ("last_rejected_at", models.DateTimeField(blank=True, null=True)),
                ("throttled_hits", models.BigIntegerField(default=0)),
                ("last_throttled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_throttled_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("key_ip", "One address on one key"),
                            ("key", "One key"),
                            ("global", "Whole deployment"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("dropped_chunks", models.BigIntegerField(default=0)),
                (
                    "last_drop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("disabled", "Recording is switched off"),
                            ("sampling", "Session not selected"),
                            ("throttle", "Rate limit"),
                            ("bytes", "Session byte cap"),
                            ("oversize", "Chunk too large"),
                            ("invalid", "Malformed chunk"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("last_drop_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecordingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enabled", models.BooleanField(default=False)),
                ("sample_pct", models.PositiveSmallIntegerField(default=100)),
                (
                    "mask_mode",
                    models.CharField(
                        choices=[
                            ("strict", "Strict: all text and images"),
                            ("balanced", "Balanced: numbers and email addresses"),
                            ("relaxed", "Relaxed: form fields only"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                ("mask_selectors", models.JSONField(blank=True, default=list)),
                ("unmask_selectors", models.JSONField(blank=True, default=list)),
                ("block_selectors", models.JSONField(blank=True, default=list)),
                ("consent_required", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording_settings",
                        to="oss_clarity.site",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "recording settings",
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(max_length=64)),
                (
                    "visitor_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("complete", "Complete"),
                            ("capped", "Capped"),
                            ("truncated", "Truncated"),
                        ],
                        default="recording",
                        max_length=10,
                    ),
                ),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not stopped"),
                            ("bytes", "Byte cap"),
                            ("pages", "Page cap"),
                            ("time", "Time cap"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "mask_mode",
                    models.CharField(
                        choices=[
                            ("strict", "Strict: all text and images"),
                            ("balanced", "Balanced: numbers and email addresses"),
                            ("relaxed", "Relaxed: form fields only"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("last_event_at", models.DateTimeField()),
                ("duration_ms", models.BigIntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                ("chunk_count", models.IntegerField(default=0)),
                ("event_count", models.IntegerField(default=0)),
                ("byte_size", models.BigIntegerField(default=0)),
                ("rage_clicks", models.IntegerField(default=0)),
                ("dead_clicks", models.IntegerField(default=0)),
                ("error_clicks", models.IntegerField(default=0)),
                ("script_errors", models.IntegerField(default=0)),
                ("hesitations", models.IntegerField(default=0)),
                ("near_misses", models.IntegerField(default=0)),
                ("scroll_hunts", models.IntegerField(default=0)),
                ("form_skips", models.IntegerField(default=0)),
                ("form_refills", models.IntegerField(default=0)),
                ("form_abandons", models.IntegerField(default=0)),
                ("repeat_submits", models.IntegerField(default=0)),
                ("copy_outs", models.IntegerField(default=0)),
                ("idle_exits", models.IntegerField(default=0)),
                ("quick_backs", models.IntegerField(default=0)),
                ("loops", models.IntegerField(default=0)),
                ("markers", models.JSONField(blank=True, default=list)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="oss_clarity.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hit_type",
                    models.CharField(
                        choices=[
                            ("pageview", "Page view"),
                            ("click", "Click"),
                            ("pageleave", "Page leave"),
                        ],
                        default="pageview",
                        max_length=10,
                    ),
                ),
                ("session_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "visitor_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("sequence", models.IntegerField(blank=True, null=True)),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("url", models.TextField(blank=True, default="")),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("referrer", models.TextField(blank=True, default="")),
                (
                    "device_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("browser", models.CharField(blank=True, default="", max_length=40)),
                ("os", models.CharField(blank=True, default="", max_length=40)),
                ("is_bot", models.BooleanField(default=False)),
                ("element_selector", models.CharField(blank=True, default="", max_length=255)),
                ("element_text", models.CharField(blank=True, default="", max_length=200)),
                ("element_href", models.TextField(blank=True, default="")),
                ("page_region", models.CharField(blank=True, default="", max_length=64)),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
                ("rel_x", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("rel_y", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("viewport_w", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_h", models.PositiveIntegerField(blank=True, null=True)),
                ("page_h", models.IntegerField(blank=True, null=True)),
                ("scroll_depth_pct", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("active_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="oss_clarity.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeatmapScrollBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=512)),
                (
                    "device_class",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=10,
                    ),
                ),
                ("day", models.DateField()),
                ("depth_decile", models.PositiveSmallIntegerField()),
                ("views", models.IntegerField(default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heatmap_scrolls",
                        to="oss_clarity.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeatmapPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=512)),
                (
                    "device_class",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=10,
                    ),
                ),
                ("day", models.DateField()),
                ("pageviews", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("pageleaves", models.IntegerField(default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heatmap_pages",
                        to="oss_clarity.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeatmapClickBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=512)),
                (
                    "device_class",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=10,
                    ),
                ),
                ("day", models.DateField()),
                ("selector_hash", models.CharField(blank=True, default="", max_length=16)),
                ("selector", models.CharField(blank=True, default="", max_length=255)),
                ("page_region", models.CharField(blank=True, default="", max_length=64)),
                ("bucket_x", models.PositiveSmallIntegerField()),
                ("bucket_y", models.PositiveSmallIntegerField()),
                ("count", models.IntegerField(default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heatmap_clicks",
                        to="oss_clarity.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordingChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("page_id", models.CharField(max_length=36)),
                ("page_seq", models.IntegerField()),
                ("chunk_seq", models.IntegerField()),
                ("url", models.TextField(blank=True, default="")),
                ("first_ts", models.BigIntegerField()),
                ("last_ts", models.BigIntegerField()),
                ("event_count", models.IntegerField(default=0)),
                ("byte_size", models.IntegerField(default=0)),
                ("storage_key", models.CharField(max_length=512)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="oss_clarity.recording",
                    ),
                ),
            ],
            options={
                "ordering": ["page_seq", "chunk_seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recording", "page_id", "chunk_seq"), name="oc_chunk_per_page"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionNavigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(max_length=64)),
                (
                    "visitor_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("quick_backs", models.IntegerField(default=0)),
                ("loops", models.IntegerField(default=0)),
                ("occurrences", models.JSONField(blank=True, default=list)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation",
                        to="oss_clarity.site",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["site", "started_at"], name="oc_nav_site_started")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "session_id"), name="oc_navigation_per_session"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(fields=["site", "-started_at"], name="oc_rec_site_started"),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(fields=["status", "last_event_at"], name="oc_rec_status_last"),
        ),
        migrations.AddConstraint(
            model_name="recording",
            constraint=models.UniqueConstraint(
                fields=("site", "session_id"), name="oc_recording_per_session"
            ),
        ),
        migrations.AddIndex(
            model_name="hit",
            index=models.Index(fields=["site", "-created_at"], name="oc_hit_site_created"),
        ),
        migrations.AddIndex(
            model_name="hit",
            index=models.Index(fields=["created_at"], name="oc_hit_created"),
        ),
        migrations.AddIndex(
            model_name="hit",
            index=models.Index(fields=["site", "path"], name="oc_hit_site_path"),
        ),
        migrations.AddIndex(
            model_name="hit",
            index=models.Index(
                fields=["site", "session_id", "created_at"], name="oc_hit_site_session"
            ),
        ),
        migrations.AddIndex(
            model_name="heatmapscrollbucket",
            index=models.Index(fields=["site", "day"], name="oc_hm_scroll_site_day"),
        ),
        migrations.AddConstraint(
            model_name="heatmapscrollbucket",
            constraint=models.UniqueConstraint(
                fields=("site", "path", "device_class", "day", "depth_decile"),
                name="oc_heatmap_scroll_bucket",
            ),
        ),
        migrations.AddIndex(
            model_name="heatmappage",
            index=models.Index(fields=["site", "day"], name="oc_hm_page_site_day"),
        ),
        migrations.AddConstraint(
            model_name="heatmappage",
            constraint=models.UniqueConstraint(
                fields=("site", "path", "device_class", "day"), name="oc_heatmap_page_day"
            ),
        ),
        migrations.AddIndex(
            model_name="heatmapclickbucket",
            index=models.Index(
                fields=["site", "path", "device_class", "day"], name="oc_hm_click_page"
            ),
        ),
        migrations.AddIndex(
            model_name="heatmapclickbucket",
            index=models.Index(fields=["site", "day"], name="oc_hm_click_site_day"),
        ),
    ]
